// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { config } from "dotenv"
import { resolve } from "node:path"
import { defineConfig, env } from "prisma/config"

// Load the root .env (two levels up), independent of the cwd Prisma is run from.
config({ path: resolve(import.meta.dirname, "../../.env") })

export default defineConfig({
    schema: "prisma/schema.prisma",
    migrations: {
        path: "prisma/migrations"
    },
    datasource: {
        url: env("DATABASE_URL")
    }
})
